name: grid_name_app
version: 0.1.0
publish_to: 'none'
description: 3x3 그리드에 명칭을 입력할 수 있는 Flutter 예제
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
