debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.thc.sprapi: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:mysql://www.adapter-gwangalli.com:3306/scmuinguard?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: ivill0080@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
sql.init.mode: always
springdoc:
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
